### ISSUE TITLE
module declares its path as: github.com/terra-project/terra.go

### ISSUE THREAD

**Issue by scrawld** [terra-money/terra.go#8]
go: finding module for package github.com/terra-money/terra.go/key
go: found github.com/terra-money/terra.go/key in github.com/terra-money/terra.go v1.0.0
go: test_func imports
        github.com/terra-money/terra.go/key: github.com/terra-money/terra.go@v1.0.0: parsing go.mod:
        module declares its path as: github.com/terra-project/terra.go
                but was required as: github.com/terra-money/terra.go

**Comment by TedHoryczun** [comment]
I can confirm this. I'm doing: 
import ( "github.com/terra-project/terra.go/client") 

to get the client instead of :  
github.com/terra-project/terra.go/client.
